/**
 * Script to generate filters.ts from the server's schema.yaml
 * 
 * This ensures the client filter options stay in sync with the database schema,
 * maintaining a single source of truth in schema.yaml.
 * 
 * Run manually: npm run generate:filters
 * Runs automatically: on dev/build (via package.json scripts)
 * 
 * See docs/fixes/2026-01-26_changelog.md for more details.
 */

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const SCHEMA_YAML_CANDIDATES = [
  path.join(__dirname, '..', 'schema.yaml'), // Docker build context (client/schema.yaml)
  path.join(__dirname, '..', '..', 'server', 'schema.yaml'), // Local repo (Dashboard/server/schema.yaml)
];
const SCHEMA_YAML_PATH = SCHEMA_YAML_CANDIDATES.find((candidate) => fs.existsSync(candidate));
const FILTERS_TS_PATH = path.join(__dirname, '..', 'src', 'config', 'filters.ts');
const q = (value) => JSON.stringify(value);

function normalizeColumns(columns) {
  if (Array.isArray(columns)) {
    return columns;
  }

  if (columns && typeof columns === 'object') {
    return Object.entries(columns).map(([name, definition]) => ({
      name,
      ...definition,
    }));
  }

  throw new Error('dim_event.columns must be an array or object map');
}

try {
  if (!SCHEMA_YAML_PATH) {
    throw new Error(
      `schema.yaml not found. Checked: ${SCHEMA_YAML_CANDIDATES.join(', ')}`
    );
  }

  // Read and parse schema.yaml
  const yamlContent = fs.readFileSync(SCHEMA_YAML_PATH, 'utf8');
  const schema = yaml.load(yamlContent);

  // Extract filter options from dim_event table columns
  const dimEvent = schema.tables?.dim_event;
  if (!dimEvent) {
    throw new Error('dim_event table not found in schema.yaml');
  }

  // Build filter options from columns that have filter config
  const filterOptions = {};
  const filterColumns = [];

  for (const column of normalizeColumns(dimEvent.columns)) {
    if (column.filter) {
      const displayName = column.filter.display_name;
      filterOptions[displayName] = {
        column: column.name,
        order: column.filter.order,
        values: column.filter.values || [],
      };
      filterColumns.push({
        name: column.name,
        displayName: displayName,
        order: column.filter.order,
        values: column.filter.values || [],
      });
    }
  }

  // Sort by order for consistent output
  filterColumns.sort((a, b) => a.order - b.order);

  // Generate TypeScript file content
  const tsContent = `/**
 * Filter Configuration
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is automatically generated from server/schema.yaml
 * by scripts/generate-filters.js
 * 
 * To modify filter options:
 * 1. Edit server/schema.yaml (dim_event table, column filter sections)
 * 2. Run: npm run generate:filters
 * Or it will be automatically regenerated on next build/dev
 * 
 * See docs/fixes/2026-01-26_changelog.md for version management guide.
 */

import type { FilterOptions } from '@/types/api';

/**
 * Default filter options (single source of truth from schema.yaml)
 * Used as fallback while loading from server or if server is unavailable.
 */
export const DEFAULT_FILTER_OPTIONS: FilterOptions = {
${Object.entries(filterOptions)
  .sort((a, b) => a[1].order - b[1].order)
  .map(([displayName, config]) => {
    const valuesStr = config.values.map(v => `      ${q(v)}`).join(',\n');
    return `  ${q(displayName)}: {
    column: ${q(config.column)},
    order: ${config.order},
    values: [
${valuesStr},
    ],
  }`;
  })
  .join(',\n')}
};

/**
 * Filter column definitions for type-safe access
 */
export const FILTER_COLUMNS = [
${filterColumns.map(col => `  {
    name: ${q(col.name)},
    displayName: ${q(col.displayName)},
    order: ${col.order},
  }`).join(',\n')}
] as const;

/**
 * Filter display names in order (for UI rendering)
 */
export const FILTER_DISPLAY_NAMES = [
${filterColumns.map(col => `  ${q(col.displayName)}`).join(',\n')}
] as const;

/**
 * Map from column name to display name
 */
export const COLUMN_TO_DISPLAY_NAME: Record<string, string> = {
${filterColumns.map(col => `  ${q(col.name)}: ${q(col.displayName)}`).join(',\n')}
};

/**
 * Map from display name to column name
 */
export const DISPLAY_NAME_TO_COLUMN: Record<string, string> = {
${filterColumns.map(col => `  ${q(col.displayName)}: ${q(col.name)}`).join(',\n')}
};

/**
 * Get filter values for a specific column
 */
export function getFilterValues(columnOrDisplayName: string): string[] {
  // Try as display name first
  if (DEFAULT_FILTER_OPTIONS[columnOrDisplayName]) {
    return DEFAULT_FILTER_OPTIONS[columnOrDisplayName].values;
  }
  
  // Try as column name
  const displayName = COLUMN_TO_DISPLAY_NAME[columnOrDisplayName];
  if (displayName && DEFAULT_FILTER_OPTIONS[displayName]) {
    return DEFAULT_FILTER_OPTIONS[displayName].values;
  }
  
  return [];
}

/**
 * Check if a value is valid for a filter
 */
export function isValidFilterValue(columnOrDisplayName: string, value: string): boolean {
  return getFilterValues(columnOrDisplayName).includes(value);
}
`;

  // Write TypeScript file
  fs.writeFileSync(FILTERS_TS_PATH, tsContent, 'utf8');
  
  const filterCount = Object.keys(filterOptions).length;
  console.log(`✓ Successfully generated filters.ts (${filterCount} filters) from schema.yaml`);
} catch (error) {
  console.error('✗ Error generating filters.ts:', error.message);
  process.exit(1);
}
