/**
 * Script to generate version.ts from the root VERSION file
 * 
 * This ensures the client uses the same version as the server,
 * maintaining a single source of truth for version management.
 * 
 * Run manually: npm run generate:version
 * Runs automatically: on dev/build (via package.json scripts)
 */

const fs = require('fs');
const path = require('path');

const VERSION_FILE_CANDIDATES = [
  path.join(__dirname, '..', 'VERSION'), // Docker build context (client/VERSION)
  path.join(__dirname, '..', '..', 'VERSION'), // Local repo / Docker /app root (Dashboard/VERSION)
];
const VERSION_FILE_PATH = VERSION_FILE_CANDIDATES.find((candidate) => fs.existsSync(candidate));
const VERSION_TS_PATH = path.join(__dirname, '..', 'src', 'config', 'version.ts');

try {
  if (!VERSION_FILE_PATH) {
    throw new Error(
      `VERSION file not found. Checked: ${VERSION_FILE_CANDIDATES.join(', ')}`
    );
  }

  const version = fs.readFileSync(VERSION_FILE_PATH, 'utf8').trim();
  
  if (!version || !/^\d+\.\d+\.\d+/.test(version)) {
    throw new Error(`Invalid version format: "${version}". Expected semver (e.g., 1.0.0)`);
  }

  // Generate TypeScript file content
  const tsContent = `/**
 * Application Version Configuration
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is automatically generated from the root VERSION file
 * by scripts/generate-version.js
 * 
 * To change the version:
 * 1. Edit the root VERSION file
 * 2. Run: npm run generate:version
 * Or it will be automatically regenerated on next build/dev
 * 
 * See docs/fixes/2026-01-26_changelog.md for version management guide.
 */

/**
 * Application version (single source of truth from root VERSION file)
 */
export const CLIENT_VERSION = "${version}";

/**
 * Get formatted version string with 'v' prefix for display
 */
export function getClientVersion(): string {
  return \`v\${CLIENT_VERSION}\`;
}

/**
 * Get raw version number without prefix
 */
export function getClientVersionRaw(): string {
  return CLIENT_VERSION;
}

/**
 * Parse version string into components
 */
export function parseVersion(version: string): { major: number; minor: number; patch: number } {
  const [major = 0, minor = 0, patch = 0] = version.split('.').map(Number);
  return { major, minor, patch };
}

/**
 * Compare two version strings
 * @returns -1 if v1 < v2, 0 if v1 === v2, 1 if v1 > v2
 */
export function compareVersions(v1: string, v2: string): -1 | 0 | 1 {
  const parts1 = v1.split('.').map(Number);
  const parts2 = v2.split('.').map(Number);
  
  for (let i = 0; i < Math.max(parts1.length, parts2.length); i++) {
    const part1 = parts1[i] || 0;
    const part2 = parts2[i] || 0;
    
    if (part1 < part2) return -1;
    if (part1 > part2) return 1;
  }
  
  return 0;
}

/**
 * Check if client version meets minimum required version
 */
export function isVersionCompatible(clientVersion: string, minVersion: string): boolean {
  return compareVersions(clientVersion, minVersion) >= 0;
}
`;

  // Write TypeScript file
  fs.writeFileSync(VERSION_TS_PATH, tsContent, 'utf8');
  
  console.log(`✓ Successfully generated version.ts (v${version}) from ${VERSION_FILE_PATH}`);
} catch (error) {
  console.error('✗ Error generating version.ts:', error.message);
  process.exit(1);
}
