/**
 * Filter Configuration
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is automatically generated from server/schema.yaml
 * by scripts/generate-filters.js
 * 
 * To modify filter options:
 * 1. Edit server/schema.yaml (dim_event table, column filter sections)
 * 2. Run: npm run generate:filters
 * Or it will be automatically regenerated on next build/dev
 * 
 * See docs/fixes/2026-01-26_changelog.md for version management guide.
 */

import type { FilterOptions } from '@/types/api';

/**
 * Default filter options (single source of truth from schema.yaml)
 * Used as fallback while loading from server or if server is unavailable.
 */
export const DEFAULT_FILTER_OPTIONS: FilterOptions = {
  "Status": {
    column: "status",
    order: 1,
    values: [
      "Approved",
      "Obsolete",
      "Pending",
    ],
  },
  "RFQ": {
    column: "rfq",
    order: 2,
    values: [
      "Applicable",
      "Not Applicable",
    ],
  },
  "DV": {
    column: "dv",
    order: 3,
    values: [
      "Applicable",
      "Not Applicable",
    ],
  },
  "PV": {
    column: "pv",
    order: 4,
    values: [
      "Applicable",
      "Not Applicable",
    ],
  },
  "Post-Prod": {
    column: "post_prod",
    order: 5,
    values: [
      "Applicable",
      "Not Applicable",
    ],
  },
  "Suspension Component": {
    column: "suspension_component",
    order: 6,
    values: [
      "A-Arm (UCA)",
      "A-Arm (LCA)",
      "L-Arm",
      "H-Arm",
      "Trailing Arm",
      "Tension Link",
      "Lateral Link",
      "Upper Trailing Link",
      "Lower Trailing Link",
      "Camber Link",
      "Spring Link",
      "Toe Link",
    ],
  },
  "Axle Location": {
    column: "axle_location",
    order: 7,
    values: [
      "Front",
      "Rear",
    ],
  },
  "Gross Vehicle Weight Range (lbs)": {
    column: "gross_vehicle_weight_range_lbs",
    order: 8,
    values: [
      "1000-1500",
      "1500-2000",
      "2000-2500",
      "2500-3000",
      "3000-3500",
      "3500-4000",
      "4000-4500",
      "4500-5000",
      "5000-5500",
      "5500-6000",
      "6000-6500",
      "6500-7000",
      "7000-7500",
      "7500-8000",
      "8000-8500",
      "8500-9000",
      "9000-9500",
      "9500-10000",
    ],
  },
  "FGAWR Range (lbs)": {
    column: "fgawr_range_lbs",
    order: 9,
    values: [
      "1000-1500",
      "1500-2000",
      "2000-2500",
      "2500-3000",
      "3000-3500",
      "3500-4000",
      "4000-4500",
      "4500-5000",
      "5000-5500",
      "5500-6000",
      "6000-6500",
      "6500-7000",
      "7000-7500",
      "7500-8000",
      "8000-8500",
      "8500-9000",
      "9000-9500",
      "9500-10000",
    ],
  },
  "RGAWR Range (lbs)": {
    column: "rgawr_range_lbs",
    order: 10,
    values: [
      "1000-1500",
      "1500-2000",
      "2000-2500",
      "2500-3000",
      "3000-3500",
      "3500-4000",
      "4000-4500",
      "4500-5000",
      "5000-5500",
      "5500-6000",
      "6000-6500",
      "6500-7000",
      "7000-7500",
      "7500-8000",
      "8000-8500",
      "8500-9000",
      "9000-9500",
      "9500-10000",
    ],
  },
  "Drive Type": {
    column: "drive_type",
    order: 11,
    values: [
      "ICE",
      "BEV",
      "PHEV",
    ],
  },
  "Mat'l & Const": {
    column: "material_construction",
    order: 12,
    values: [
      "Steel (stamped & welded)",
      "Steel (forged)",
      "Steel (stamped)",
      "Ductile Iron (cast)",
      "Aluminum (forged)",
      "Aluminum (cast)",
    ],
  },
  "Steering": {
    column: "steering_position",
    order: 13,
    values: [
      "RHS",
      "LHS",
    ],
  },
  "Damper Type": {
    column: "damper_type",
    order: 14,
    values: [
      "Coil Over",
      "Air Suspension",
    ],
  },
  "Vehicle Type": {
    column: "vehicle_type",
    order: 15,
    values: [
      "Sedan",
      "Truck",
      "Van",
      "SUV",
      "Heavy Duty",
      "Off-Road",
      "Other",
    ],
  }
};

/**
 * Filter column definitions for type-safe access
 */
export const FILTER_COLUMNS = [
  {
    name: "status",
    displayName: "Status",
    order: 1,
  },
  {
    name: "rfq",
    displayName: "RFQ",
    order: 2,
  },
  {
    name: "dv",
    displayName: "DV",
    order: 3,
  },
  {
    name: "pv",
    displayName: "PV",
    order: 4,
  },
  {
    name: "post_prod",
    displayName: "Post-Prod",
    order: 5,
  },
  {
    name: "suspension_component",
    displayName: "Suspension Component",
    order: 6,
  },
  {
    name: "axle_location",
    displayName: "Axle Location",
    order: 7,
  },
  {
    name: "gross_vehicle_weight_range_lbs",
    displayName: "Gross Vehicle Weight Range (lbs)",
    order: 8,
  },
  {
    name: "fgawr_range_lbs",
    displayName: "FGAWR Range (lbs)",
    order: 9,
  },
  {
    name: "rgawr_range_lbs",
    displayName: "RGAWR Range (lbs)",
    order: 10,
  },
  {
    name: "drive_type",
    displayName: "Drive Type",
    order: 11,
  },
  {
    name: "material_construction",
    displayName: "Mat'l & Const",
    order: 12,
  },
  {
    name: "steering_position",
    displayName: "Steering",
    order: 13,
  },
  {
    name: "damper_type",
    displayName: "Damper Type",
    order: 14,
  },
  {
    name: "vehicle_type",
    displayName: "Vehicle Type",
    order: 15,
  }
] as const;

/**
 * Filter display names in order (for UI rendering)
 */
export const FILTER_DISPLAY_NAMES = [
  "Status",
  "RFQ",
  "DV",
  "PV",
  "Post-Prod",
  "Suspension Component",
  "Axle Location",
  "Gross Vehicle Weight Range (lbs)",
  "FGAWR Range (lbs)",
  "RGAWR Range (lbs)",
  "Drive Type",
  "Mat'l & Const",
  "Steering",
  "Damper Type",
  "Vehicle Type"
] as const;

/**
 * Map from column name to display name
 */
export const COLUMN_TO_DISPLAY_NAME: Record<string, string> = {
  "status": "Status",
  "rfq": "RFQ",
  "dv": "DV",
  "pv": "PV",
  "post_prod": "Post-Prod",
  "suspension_component": "Suspension Component",
  "axle_location": "Axle Location",
  "gross_vehicle_weight_range_lbs": "Gross Vehicle Weight Range (lbs)",
  "fgawr_range_lbs": "FGAWR Range (lbs)",
  "rgawr_range_lbs": "RGAWR Range (lbs)",
  "drive_type": "Drive Type",
  "material_construction": "Mat'l & Const",
  "steering_position": "Steering",
  "damper_type": "Damper Type",
  "vehicle_type": "Vehicle Type"
};

/**
 * Map from display name to column name
 */
export const DISPLAY_NAME_TO_COLUMN: Record<string, string> = {
  "Status": "status",
  "RFQ": "rfq",
  "DV": "dv",
  "PV": "pv",
  "Post-Prod": "post_prod",
  "Suspension Component": "suspension_component",
  "Axle Location": "axle_location",
  "Gross Vehicle Weight Range (lbs)": "gross_vehicle_weight_range_lbs",
  "FGAWR Range (lbs)": "fgawr_range_lbs",
  "RGAWR Range (lbs)": "rgawr_range_lbs",
  "Drive Type": "drive_type",
  "Mat'l & Const": "material_construction",
  "Steering": "steering_position",
  "Damper Type": "damper_type",
  "Vehicle Type": "vehicle_type"
};

/**
 * Get filter values for a specific column
 */
export function getFilterValues(columnOrDisplayName: string): string[] {
  // Try as display name first
  if (DEFAULT_FILTER_OPTIONS[columnOrDisplayName]) {
    return DEFAULT_FILTER_OPTIONS[columnOrDisplayName].values;
  }
  
  // Try as column name
  const displayName = COLUMN_TO_DISPLAY_NAME[columnOrDisplayName];
  if (displayName && DEFAULT_FILTER_OPTIONS[displayName]) {
    return DEFAULT_FILTER_OPTIONS[displayName].values;
  }
  
  return [];
}

/**
 * Check if a value is valid for a filter
 */
export function isValidFilterValue(columnOrDisplayName: string, value: string): boolean {
  return getFilterValues(columnOrDisplayName).includes(value);
}
