/**
 * Plot Settings
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is automatically generated from settings.yaml by scripts/generate-settings.js
 * 
 * To modify settings, edit client/settings.yaml and run: npm run generate:settings
 * Or it will be automatically regenerated on next build/dev
 */

// Plot dimensions
export const PLOT_WIDTH = 2100;
export const PLOT_HEIGHT = 1200;

// Plot configuration interface
export interface PlotConfig {
  title: string;
  x_label: string;
  y_label: string;
}

// Default plot keys for the grid (these come from channel_map)
// Dictionary mapping plot keys to configuration (title and axis labels)
export const DEFAULT_PLOT_KEYS: Record<string, PlotConfig> = {
  'bj_xy_force_plot': {
    title: 'BJ XY Force',
    x_label: 'X-Component (N)',
    y_label: 'Y-Component (N)',
  },
  'bj_xz_force_plot': {
    title: 'BJ XZ Force',
    x_label: 'X-Component (N)',
    y_label: 'Z-Component (N)',
  },
  'shock_xy_force_plot': {
    title: 'Shock XY Force',
    x_label: 'X-Component (N)',
    y_label: 'Y-Component (N)',
  },
  'shock_xz_force_plot': {
    title: 'Shock XZ Force',
    x_label: 'X-Component (N)',
    y_label: 'Z-Component (N)',
  },
  'bushing_f_xy_force_plot': {
    title: 'Bushing F XY Moment',
    x_label: 'X-Component (N)',
    y_label: 'Y-Component (N)',
  },
  'bushing_f_xz_force_plot': {
    title: 'Bushing F XZ Moment',
    x_label: 'X-Component (N)',
    y_label: 'Z-Component (N)',
  },
  'bushing_r_xy_force_plot': {
    title: 'Bushing R XY Moment',
    x_label: 'X-Component (N)',
    y_label: 'Y-Component (N)',
  },
  'bushing_r_xz_force_plot': {
    title: 'Bushing R XZ Moment',
    x_label: 'X-Component (N)',
    y_label: 'Z-Component (N)',
  },
};

// Array of plot keys (for API calls and iteration)
export const DEFAULT_PLOT_KEYS_ARRAY = Object.keys(DEFAULT_PLOT_KEYS) as readonly string[];

// Helper function to get display title for a plot key
export function getPlotDisplayTitle(plotKey: string): string {
  return DEFAULT_PLOT_KEYS[plotKey]?.title || plotKey.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

// Helper function to get X axis label for a plot key
export function getPlotXLabel(plotKey: string): string {
  return DEFAULT_PLOT_KEYS[plotKey]?.x_label || 'X';
}

// Helper function to get Y axis label for a plot key
export function getPlotYLabel(plotKey: string): string {
  return DEFAULT_PLOT_KEYS[plotKey]?.y_label || 'Y';
}

// Helper function to get full plot configuration for a plot key
export function getPlotConfig(plotKey: string): PlotConfig | null {
  return DEFAULT_PLOT_KEYS[plotKey] || null;
}

// Opacity settings
export const DEFAULT_BASELINE_OPACITY = 0.5;
export const NEW_DATA_OPACITY = 1;

// Grid layout options
export const GRID_COLUMN_OPTIONS = [2, 3, 4] as const;
export const DEFAULT_GRID_COLUMNS = 3;

// Color palette for grouping (colorblind-friendly)
export const COLOR_PALETTE = [
  '#3b82f6',
  '#f97316',
  '#22c55e',
  '#a855f7',
  '#ef4444',
  '#06b6d4',
  '#eab308',
  '#ec4899',
] as const;

// Max groups before showing warning
export const MAX_DISTINCT_GROUPS = 8;

// Debounce timings (ms)
export const SESSION_SAVE_DEBOUNCE = 500;
export const FILTER_DEBOUNCE = 300;
