/**
 * Application Version Configuration
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is automatically generated from the root VERSION file
 * by scripts/generate-version.js
 * 
 * To change the version:
 * 1. Edit the root VERSION file
 * 2. Run: npm run generate:version
 * Or it will be automatically regenerated on next build/dev
 * 
 * See docs/fixes/2026-01-26_changelog.md for version management guide.
 */

/**
 * Application version (single source of truth from root VERSION file)
 */
export const CLIENT_VERSION = "1.3.7";

/**
 * Get formatted version string with 'v' prefix for display
 */
export function getClientVersion(): string {
  return `v${CLIENT_VERSION}`;
}

/**
 * Get raw version number without prefix
 */
export function getClientVersionRaw(): string {
  return CLIENT_VERSION;
}

/**
 * Parse version string into components
 */
export function parseVersion(version: string): { major: number; minor: number; patch: number } {
  const [major = 0, minor = 0, patch = 0] = version.split('.').map(Number);
  return { major, minor, patch };
}

/**
 * Compare two version strings
 * @returns -1 if v1 < v2, 0 if v1 === v2, 1 if v1 > v2
 */
export function compareVersions(v1: string, v2: string): -1 | 0 | 1 {
  const parts1 = v1.split('.').map(Number);
  const parts2 = v2.split('.').map(Number);
  
  for (let i = 0; i < Math.max(parts1.length, parts2.length); i++) {
    const part1 = parts1[i] || 0;
    const part2 = parts2[i] || 0;
    
    if (part1 < part2) return -1;
    if (part1 > part2) return 1;
  }
  
  return 0;
}

/**
 * Check if client version meets minimum required version
 */
export function isVersionCompatible(clientVersion: string, minVersion: string): boolean {
  return compareVersions(clientVersion, minVersion) >= 0;
}
